### ISSUE TITLE
high tag number is not decoded as expected

### ISSUE THREAD

**Issue by highmtworks** [atesgoral/node-asn1-tree#8]
high tag number is not decoded as expected.

How to reproduce:
```
const asn1 = require('asn1-tree');
const decoded = asn1.decode(Buffer.from([0x1f, 0x81, 0x00, 0x00]));
console.log(decoded);
```

Expected:
```
{ cls: 0, form: 0, tagCode: 128, value: <Buffer > }
```

Actual:
```
{ cls: 0, form: 0, tagCode: 256, value: <Buffer > }
```

Maybe:
```
--- index.js.orig
+++ index.js
@@ -17,7 +17,7 @@
     do {
       byte = buffer.readUInt8(bytesRead);
       bytesRead += 1;
-      tagCode = (tagCode << 8) | (byte & 0x7f);
+      tagCode = (tagCode << 7) | (byte & 0x7f);
     } while (byte & 0x80);
   }
```

Anyway, thank you for this convenient tool.

**Comment by atesgoral** [comment]
@highmtworks @shokuie Could you point me to a spec around high tag numbers?

**Comment by highmtworks** [comment]
Sorry for my poor information.

https://www.itu.int/rec/T-REC-X.690-201508-I/en
8.1.2.4 explains this. 
Bit 8 of each octet just indicates being followed by a subsequent octet and is ignored.

http://luca.ntop.org/Teaching/Appunti/asn1.html
3.1 also says base is 128, not 256.

And below is the result of another library [asn1js](https://www.npmjs.com/package/asn1js):
```
const toArrayBuffer = (bin) => {
  const ab = new ArrayBuffer(bin.length);
  const view = new Uint8Array(ab);
  for (let i = 0; i < bin.length; ++i) {
    view[i] = bin[i];
  }
  return ab;
};
const asn1js = require('asn1js');
const parsed = asn1js.fromBER(toArrayBuffer(Buffer.from([0x1f, 0x81, 0x00, 0x00])));
console.log(parsed.result.idBlock.tagNumber);
// -> 128
```

**Comment by shokuie** [comment]
@atesgoral 

> Identifier octets. There are two forms: low tag number (for tag numbers between 0 and 30) and high tag number (for tag numbers 31 and greater).

> Low-tag-number form. One octet. Bits 8 and 7 specify the class (see Table 2), bit 6 has the value "0," indicating that the encoding is primitive, and bits 5-1 give the tag number.

> High-tag-number form. Two or more octets. The first octet is as in low-tag-number form, except that bits 5-1 all have value "1." Second and following octets give the tag number, base 128, most significant digit first, with as few digits as possible, and with the bit 8 of each octet except the last set to "1."

Looks like the code change makes sense. @highmtworks Can you please add a test case that covers a high tag greater than 256 (a tag with three octets). Looks like I've never tested it for tags greater than 128.

**Comment by atesgoral** [comment]
@highmtworks @shokuie Thank you both!

v0.1.1 published with the fix.
